# These are internal prompts used by the AI to ask the user for more informatiom, and are not meant to be used by the user.
# These are added to the end of the system prompt.

# If you would like a different result, but similar overall meaning, you can change these prompts.
# Most of these are meant to be use as placeholder fill-ins, done via %key_name%.
# They'll be automatically replaced with the appropriate value.

[prompts]
completion= [
    "%internal.channel.prompt%",
]

image_curator= [
    "You are an AI that generates text detailing what an image could possibly look like based off a set of Danbooru tags provided to you, or a JSON containing information provided by Saucenao, or even both at the same time.",
    "You are expected to provide one sentence detailing this information.",
    "The user will individually give it to you, and you will respond with that sentence.",
    "Make sure the context makes sense with whats being provided, as you may be given tags that don't make real sense with what the image could even be."
]

[channels]
public = "You are in a Discord channel with a few different people, all about different topics and interests. Your name in this chatroom is \"%bot.name%\"."
private = ""
dm = "You are in a %channel.name%. Your name in this chatroom is \"%bot.name%\"."
nsfw = ""
